/*
 * Copyright (c) 2025 Quanti Pixels
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
package com.quantipixels.ogiri.samples.java.entity;

import com.quantipixels.ogiri.security.tokens.OgiriBaseToken;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.time.Instant;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * Sample JPA Token implementation extending BaseToken.
 *
 * <p>This demonstrates how Java users should implement their own Token class for JPA/Hibernate
 * persistence. The class extends OgiriBaseToken and provides JPA annotations for column mapping and
 * constraints.
 *
 * <p>All properties implement the abstract/open properties from BaseToken, and the class includes
 * getters/setters for fields that TokenService updates.
 */
@Entity
@Table(
    name = "user_tokens",
    indexes = {
      @Index(name = "idx_user_tokens_user_id", columnList = "user_id"),
      @Index(name = "idx_user_tokens_expiry", columnList = "expiry_at"),
    },
    uniqueConstraints = {
      @UniqueConstraint(
          name = "uk_user_tokens_user_client",
          columnNames = {"user_id", "client_id"}),
    })
public class SampleToken extends OgiriBaseToken {

  /** Primary key - auto-generated by database. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /** User ID - indexed for efficient lookups. */
  @Column(name = "user_id", nullable = false)
  private Long userId;

  /** Client/application identifier - part of unique constraint with userId. */
  @Column(name = "client_id", nullable = false)
  private String client;

  /** Hashed token value (never plaintext). */
  @Column(name = "token_hash", nullable = false)
  private String token;

  /** Token type classifier ("APP" or "SUB"). */
  @Column(name = "token_type", nullable = false)
  private String tokenType = "APP";

  /** Token expiration time (UTC) - indexed for cleanup queries. */
  @Column(name = "expiry_at", nullable = false)
  private Instant expiryAt;

  /** Timestamp when token was created. Auto-populated by Hibernate on insert. */
  @CreationTimestamp
  @Column(name = "created_at", nullable = false, updatable = false)
  private Instant createdAt;

  /** Timestamp when token was last updated. Auto-updated by Hibernate on any modification. */
  @UpdateTimestamp
  @Column(name = "updated_at", nullable = false)
  private Instant updatedAt;

  /** Timestamp when token rotation last occurred. Updated by TokenService during rotation. */
  @Column(name = "token_updated_at", nullable = false)
  private Instant tokenUpdatedAt;

  /** Optional sub-token type (e.g., "device", "chat"). */
  @Column(name = "token_subtype")
  private String tokenSubtype;

  /**
   * Previous token hash (for grace period during rotation). Allows old token to work briefly while
   * new token is issued.
   */
  @Column(name = "last_token_hash")
  private String lastToken;

  /**
   * Token before last (extended grace period). For additional safety during token rotation cascade.
   */
  @Column(name = "previous_token_hash")
  private String previousToken;

  /**
   * Last timestamp this token was successfully used for authentication. Useful for monitoring and
   * cleanup of stale tokens.
   */
  @Column(name = "last_used_at")
  private Instant lastUsedAt;

  /** Default constructor for JPA. */
  public SampleToken() {
    this.createdAt = Instant.now();
    this.updatedAt = Instant.now();
    this.tokenUpdatedAt = Instant.now();
  }

  /** Constructor with required fields. */
  public SampleToken(Long userId, String client, String token, Instant expiryAt) {
    this.userId = userId;
    this.client = client;
    this.token = token;
    this.expiryAt = expiryAt;
    this.createdAt = Instant.now();
    this.updatedAt = Instant.now();
    this.tokenUpdatedAt = Instant.now();
  }

  public long getId() {
    return id;
  }

  public long getUserId() {
    return userId;
  }

  public String getClient() {
    return client;
  }

  public String getToken() {
    return token;
  }

  public String getTokenType() {
    return tokenType;
  }

  public Instant getExpiryAt() {
    return expiryAt;
  }

  public Instant getCreatedAt() {
    return createdAt;
  }

  public Instant getUpdatedAt() {
    return updatedAt;
  }

  public Instant getTokenUpdatedAt() {
    return tokenUpdatedAt;
  }

  public String getTokenSubtype() {
    return tokenSubtype;
  }

  public String getLastToken() {
    return lastToken;
  }

  public String getPreviousToken() {
    return previousToken;
  }

  public Instant getLastUsedAt() {
    return lastUsedAt;
  }

  // ==================== SETTERS ====================

  public void setId(Long id) {
    this.id = id;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public void setClient(String client) {
    this.client = client;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public void setTokenType(String tokenType) {
    this.tokenType = tokenType;
  }

  public void setExpiryAt(Instant expiryAt) {
    this.expiryAt = expiryAt;
  }

  public void setUpdatedAt(Instant updatedAt) {
    this.updatedAt = updatedAt;
  }

  public void setTokenUpdatedAt(Instant tokenUpdatedAt) {
    this.tokenUpdatedAt = tokenUpdatedAt;
  }

  public void setTokenSubtype(String tokenSubtype) {
    this.tokenSubtype = tokenSubtype;
  }

  public void setLastToken(String lastToken) {
    this.lastToken = lastToken;
  }

  public void setPreviousToken(String previousToken) {
    this.previousToken = previousToken;
  }

  public void setLastUsedAt(Instant lastUsedAt) {
    this.lastUsedAt = lastUsedAt;
  }

  // ==================== TOSTRING ====================

  @Override
  public String toString() {
    return "SampleToken{"
        + "id="
        + id
        + ", userId="
        + userId
        + ", client='"
        + client
        + '\''
        + ", tokenType='"
        + tokenType
        + '\''
        + ", expiryAt="
        + expiryAt
        + '}';
  }
}
