/*
 * Copyright (c) 2025 Quanti Pixels
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
package com.quantipixels.ogiri.jpa

import com.quantipixels.ogiri.security.tokens.OgiriBaseToken
import com.quantipixels.ogiri.security.tokens.OgiriTokenType
import jakarta.persistence.Column
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.MappedSuperclass
import jakarta.persistence.PrePersist
import jakarta.persistence.PreUpdate
import jakarta.persistence.Transient
import java.time.Instant
import org.hibernate.annotations.CreationTimestamp

/**
 * Base JPA entity with all required token fields pre-configured.
 *
 * Users extend this class and add `@Entity` + `@Table` annotations:
 * ```kotlin
 * @Entity
 * @Table(
 *     name = "tokens",
 *     indexes = [
 *         Index(name = "idx_tokens_user_id", columnList = "user_id"),
 *         Index(name = "idx_tokens_expiry", columnList = "expiry_at"),
 *     ],
 *     uniqueConstraints = [
 *         UniqueConstraint(name = "uk_tokens_user_client", columnNames = ["user_id", "client"]),
 *     ],
 * )
 * class MyToken : OgiriBaseTokenEntity()
 * ```
 *
 * All 14+ fields with proper JPA annotations are inherited:
 * - id (auto-generated)
 * - userId, client, token, tokenType
 * - expiryAt, tokenUpdatedAt, createdAt, updatedAt
 * - previousToken, lastToken, tokenSubtype
 * - lastUsedAt
 * - plainToken (transient, not persisted)
 *
 * Timestamps are managed automatically:
 * - `createdAt`: Set once on insert via `@CreationTimestamp`
 * - `updatedAt`: Updated on every save via `@PrePersist`/`@PreUpdate`
 * - `tokenUpdatedAt`: Managed by TokenService during rotation
 */
@MappedSuperclass
abstract class OgiriBaseTokenEntity : OgiriBaseToken() {

  /** Primary key - auto-generated by database. */
  @Id @GeneratedValue(strategy = GenerationType.IDENTITY) override var id: Long = 0

  /** User ID - should be indexed for efficient lookups. */
  @Column(name = "user_id", nullable = false) override var userId: Long = 0

  /** Client/application identifier - part of unique constraint with userId. */
  @Column(name = "client", nullable = false, length = 64) override var client: String = ""

  /** Hashed token value (never plaintext). */
  @Column(name = "token_hash", nullable = false, length = 512) override var token: String = ""

  /** Token type classifier ("app" or "sub"). */
  @Column(name = "token_type", nullable = false, length = 16)
  override var tokenType: String = OgiriTokenType.APP.label

  /** Token expiration time (UTC) - should be indexed for cleanup queries. */
  @Column(name = "expiry_at", nullable = false) override var expiryAt: Instant = Instant.now()

  /** Timestamp when token was created. Auto-populated by Hibernate on insert. */
  @CreationTimestamp
  @Column(name = "created_at", nullable = false, updatable = false)
  override var createdAt: Instant = Instant.EPOCH

  /** Timestamp when token was last updated. Auto-updated on any modification. */
  @Column(name = "updated_at", nullable = false) override var updatedAt: Instant = Instant.now()

  /** Timestamp when token rotation last occurred. Updated by TokenService during rotation. */
  @Column(name = "token_updated_at", nullable = false)
  override var tokenUpdatedAt: Instant = Instant.now()

  /** Optional sub-token type (e.g., "device", "chat"). */
  @Column(name = "token_subtype", length = 32) override var tokenSubtype: String? = null

  /**
   * Previous token hash (for grace period during rotation). Allows old token to work briefly while
   * new token is issued.
   */
  @Column(name = "last_token_hash", length = 512) override var lastToken: String? = null

  /** Token before last (extended grace period). For additional safety during token rotation. */
  @Column(name = "previous_token_hash", length = 512) override var previousToken: String? = null

  /**
   * Last timestamp this token was successfully used for authentication. Useful for monitoring and
   * cleanup of stale tokens.
   */
  @Column(name = "last_used_at") override var lastUsedAt: Instant? = null

  /**
   * Plain (unhashed) token value. NEVER persisted to database. Only exists in-memory temporarily
   * during token creation.
   */
  @Transient override var plainToken: String? = null

  /** Updates the updatedAt timestamp before persisting or updating. */
  @PrePersist
  @PreUpdate
  fun updateTimestamp() {
    updatedAt = Instant.now()
  }
}
