/*
 * Copyright (c) 2025 Quanti Pixels
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
package com.quantipixels.ogiri.samples.kotlin.entity

import com.quantipixels.ogiri.security.tokens.BaseToken
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Index
import jakarta.persistence.Table
import jakarta.persistence.UniqueConstraint
import java.time.Instant
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.UpdateTimestamp

/**
 * Sample JPA Token implementation extending BaseToken.
 *
 * This demonstrates how Kotlin users should implement their own Token class for JPA/Hibernate
 * persistence. The class extends BaseToken and provides JPA annotations for column mapping and
 * constraints.
 *
 * All properties implement the abstract/open properties from BaseToken, with mutable (var) fields
 * that TokenService updates during token rotation.
 */
@Entity
@Table(
    name = "user_tokens",
    indexes =
        [
            Index(name = "idx_user_tokens_user_id", columnList = "user_id"),
            Index(name = "idx_user_tokens_expiry", columnList = "expiry_at"),
        ],
    uniqueConstraints =
        [
            UniqueConstraint(
                name = "uk_user_tokens_user_client",
                columnNames = ["user_id", "client_id"],
            ),
        ],
)
data class SampleToken(
    /** Primary key - auto-generated by database. */
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) override val id: Long = 0,
    /** User ID - indexed for efficient lookups. */
    @Column(name = "user_id", nullable = false) override val userId: Long = 0,
    /** Client/application identifier - part of unique constraint with userId. */
    @Column(name = "client_id", nullable = false) override val client: String = "",
    /** Hashed token value (never plaintext). */
    @Column(name = "token_hash", nullable = false) override var token: String = "",
    /** Token type classifier ("APP" or "SUB"). */
    @Column(name = "token_type", nullable = false) override val tokenType: String = "APP",
    /** Token expiration time (UTC) - indexed for cleanup queries. */
    @Column(name = "expiry_at", nullable = false) override var expiryAt: Instant = Instant.now(),
    /** Timestamp when token was created. Auto-populated by Hibernate on insert. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    override val createdAt: Instant = Instant.now(),
    /** Timestamp when token was last updated. Auto-updated by Hibernate on any modification. */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    override val updatedAt: Instant = Instant.now(),
    /** Timestamp when token rotation last occurred. Updated by TokenService during rotation. */
    @Column(name = "token_updated_at", nullable = false)
    override var tokenUpdatedAt: Instant = Instant.now(),
    /** Optional sub-token type (e.g., "device", "chat"). */
    @Column(name = "token_subtype") override var tokenSubtype: String? = null,
    /**
     * Previous token hash (for grace period during rotation). Allows old token to work briefly
     * while new token is issued.
     */
    @Column(name = "last_token_hash") override var lastToken: String? = null,
    /**
     * Token before last (extended grace period). For additional safety during token rotation
     * cascade.
     */
    @Column(name = "previous_token_hash") override var previousToken: String? = null,
    /**
     * Last timestamp this token was successfully used for authentication. Useful for monitoring and
     * cleanup of stale tokens.
     */
    @Column(name = "last_used_at") override var lastUsedAt: Instant? = null,
) : BaseToken()
