/*
 * Copyright (c) 2025 Quanti Pixels
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
package com.quantipixels.ogiri.samples.kotlin.service

import com.quantipixels.ogiri.samples.kotlin.entity.SampleToken
import com.quantipixels.ogiri.security.config.OgiriConfigurationProperties
import com.quantipixels.ogiri.security.core.IdentifierPolicy
import com.quantipixels.ogiri.security.spi.OgiriUserDirectory
import com.quantipixels.ogiri.security.tokens.OgiriSubTokenRegistry
import com.quantipixels.ogiri.security.tokens.OgiriTokenRepository
import com.quantipixels.ogiri.security.tokens.OgiriTokenService
import com.quantipixels.ogiri.security.tokens.OgiriTokenType
import java.time.Instant
import org.springframework.context.annotation.Primary
import org.springframework.security.crypto.password.PasswordEncoder
import org.springframework.stereotype.Service

/**
 * Sample TokenService implementation for the Kotlin example app.
 *
 * This service demonstrates how users should extend TokenService and override the tokenFactory()
 * method to instantiate their custom Token class.
 *
 * In this case, we're using SampleToken (a JPA entity) as the implementation. Other users might use
 * JdbcToken (JDBC), MongoToken (MongoDB), or any other custom Token class extending BaseToken.
 *
 * The tokenFactory() method is called by TokenService when creating new tokens during
 * authentication, token rotation, and sub-token generation.
 */
@Service
@Primary
class SampleTokenService(
    tokenRepository: OgiriTokenRepository<SampleToken>,
    passwordEncoder: PasswordEncoder,
    userDirectory: OgiriUserDirectory,
    identifierPolicy: IdentifierPolicy,
    subTokenRegistry: OgiriSubTokenRegistry,
    properties: OgiriConfigurationProperties,
) :
    OgiriTokenService<SampleToken>(
        tokenRepository,
        passwordEncoder,
        userDirectory,
        identifierPolicy,
        subTokenRegistry,
        properties,
    ) {
  /**
   * Factory method for creating SampleToken instances.
   *
   * This is called by TokenService whenever a new token needs to be created:
   * - createNewAuthToken() - Creates primary APP token
   * - createOrUpdateToken() - Creates or updates any token (APP or SUB)
   * - issueSubTokens() - Creates sub-tokens (device, chat, etc.)
   *
   * The implementation simply constructs a SampleToken data class with all the required fields.
   * Since SampleToken is a JPA entity, when saved to the repository, Hibernate will handle
   * insert/update with auto-generated IDs and timestamps.
   *
   * @param userId The user ID
   * @param client The client/application identifier
   * @param hashedToken The bcrypt-hashed token value (never plaintext)
   * @param tokenType The token type (APP for primary, SUB for sub-tokens)
   * @param expiry The expiration time for this token
   * @param tokenSubtype Optional sub-token type (e.g., "device", "chat")
   * @param plainTokenValue The plain (unhashed) token - only in-memory, never persisted
   * @return A new SampleToken configured with all parameters
   */
  override fun tokenFactory(
      userId: Long,
      client: String,
      hashedToken: String,
      tokenType: OgiriTokenType,
      expiry: Instant,
      tokenSubtype: String?,
      plainTokenValue: String,
  ): SampleToken {
    // Create new token with all required fields
    val token =
        SampleToken(
            id = 0, // Auto-generated by database
            userId = userId,
            client = client,
            token = hashedToken,
            tokenType = tokenType.name, // Convert enum to string ("app" or "sub")
            expiryAt = expiry,
            tokenSubtype = tokenSubtype,
        )

    // Set the plain token for return to client (in-memory only)
    token.plainToken = plainTokenValue

    return token
  }
}
