spring.datasource.url=${OGIRI_JDBC_URL}
spring.datasource.username=${OGIRI_JDBC_USER}
spring.datasource.password=${OGIRI_JDBC_PASSWORD}
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=3000
demo.password=${OGIRI_DEMO_PASSWORD}
server.error.include-message=never
ogiri.enabled=true
